/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AdvisoriesRouteImport } from './routes/advisories'
import { Route as AiTrainingRouteImport } from './routes/ai-training'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AuditLogsRouteImport } from './routes/audit-logs'
import { Route as AutomationRouteImport } from './routes/automation'
import { Route as CitationsRouteImport } from './routes/citations'
import { Route as CitizenRouteImport } from './routes/citizen'
import { Route as CommunicationsRouteImport } from './routes/communications'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DeveloperRouteImport } from './routes/developer'
import { Route as DispatchRouteImport } from './routes/dispatch'
import { Route as DispatchHotlineRouteImport } from './routes/dispatch-hotline'
import { Route as DisputesRouteImport } from './routes/disputes'
import { Route as FinanceRouteImport } from './routes/finance'
import { Route as FinanceAnalyticsRouteImport } from './routes/finance-analytics'
import { Route as InfrastructureRouteImport } from './routes/infrastructure'
import { Route as IotRouteImport } from './routes/iot'
import { Route as LookupRouteImport } from './routes/lookup'
import { Route as MapRouteImport } from './routes/map'
import { Route as OfficerRouteImport } from './routes/officer'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SlaPerformanceRouteImport } from './routes/sla-performance'
import { Route as TransportRouteImport } from './routes/transport'
import { Route as TvDisplayRouteImport } from './routes/tv-display'
import { Route as ViolationsRouteImport } from './routes/violations'
import { Route as AnalyticsHeatmapsRouteImport } from './routes/analytics.heatmaps'
import { Route as CamerasIndexRouteImport } from './routes/cameras.index'
import { Route as CamerasCodeRouteImport } from './routes/cameras.$code'
import { Route as OfficerIndexRouteImport } from './routes/officer.index'
import { Route as OfficerDispatchesRouteImport } from './routes/officer.dispatches'
import { Route as OfficerIssueRouteImport } from './routes/officer.issue'
import { Route as OfficerScanRouteImport } from './routes/officer.scan'
import { Route as OfficersIndexRouteImport } from './routes/officers.index'
import { Route as OfficersBadgeRouteImport } from './routes/officers.$badge'
import { Route as OfficersShiftsRouteImport } from './routes/officers.shifts'
import { Route as VehiclesIndexRouteImport } from './routes/vehicles.index'
import { Route as VehiclesPlateRouteImport } from './routes/vehicles.$plate'
import { Route as PortalPayCitationIdRouteImport } from './routes/portal.pay.$citationId'
import { Route as PortalReceiptCitationIdRouteImport } from './routes/portal.receipt.$citationId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvisoriesRoute = AdvisoriesRouteImport.update({
  id: '/advisories',
  path: '/advisories',
  getParentRoute: () => rootRouteImport,
} as any)
const AiTrainingRoute = AiTrainingRouteImport.update({
  id: '/ai-training',
  path: '/ai-training',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditLogsRoute = AuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomationRoute = AutomationRouteImport.update({
  id: '/automation',
  path: '/automation',
  getParentRoute: () => rootRouteImport,
} as any)
const CitationsRoute = CitationsRouteImport.update({
  id: '/citations',
  path: '/citations',
  getParentRoute: () => rootRouteImport,
} as any)
const CitizenRoute = CitizenRouteImport.update({
  id: '/citizen',
  path: '/citizen',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunicationsRoute = CommunicationsRouteImport.update({
  id: '/communications',
  path: '/communications',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DeveloperRoute = DeveloperRouteImport.update({
  id: '/developer',
  path: '/developer',
  getParentRoute: () => rootRouteImport,
} as any)
const DispatchRoute = DispatchRouteImport.update({
  id: '/dispatch',
  path: '/dispatch',
  getParentRoute: () => rootRouteImport,
} as any)
const DispatchHotlineRoute = DispatchHotlineRouteImport.update({
  id: '/dispatch-hotline',
  path: '/dispatch-hotline',
  getParentRoute: () => rootRouteImport,
} as any)
const DisputesRoute = DisputesRouteImport.update({
  id: '/disputes',
  path: '/disputes',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceRoute = FinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceAnalyticsRoute = FinanceAnalyticsRouteImport.update({
  id: '/finance-analytics',
  path: '/finance-analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const InfrastructureRoute = InfrastructureRouteImport.update({
  id: '/infrastructure',
  path: '/infrastructure',
  getParentRoute: () => rootRouteImport,
} as any)
const IotRoute = IotRouteImport.update({
  id: '/iot',
  path: '/iot',
  getParentRoute: () => rootRouteImport,
} as any)
const LookupRoute = LookupRouteImport.update({
  id: '/lookup',
  path: '/lookup',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficerRoute = OfficerRouteImport.update({
  id: '/officer',
  path: '/officer',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SlaPerformanceRoute = SlaPerformanceRouteImport.update({
  id: '/sla-performance',
  path: '/sla-performance',
  getParentRoute: () => rootRouteImport,
} as any)
const TransportRoute = TransportRouteImport.update({
  id: '/transport',
  path: '/transport',
  getParentRoute: () => rootRouteImport,
} as any)
const TvDisplayRoute = TvDisplayRouteImport.update({
  id: '/tv-display',
  path: '/tv-display',
  getParentRoute: () => rootRouteImport,
} as any)
const ViolationsRoute = ViolationsRouteImport.update({
  id: '/violations',
  path: '/violations',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsHeatmapsRoute = AnalyticsHeatmapsRouteImport.update({
  id: '/heatmaps',
  path: '/heatmaps',
  getParentRoute: () => AnalyticsRoute,
} as any)
const CamerasIndexRoute = CamerasIndexRouteImport.update({
  id: '/cameras/',
  path: '/cameras/',
  getParentRoute: () => rootRouteImport,
} as any)
const CamerasCodeRoute = CamerasCodeRouteImport.update({
  id: '/cameras/$code',
  path: '/cameras/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficerIndexRoute = OfficerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OfficerRoute,
} as any)
const OfficerDispatchesRoute = OfficerDispatchesRouteImport.update({
  id: '/dispatches',
  path: '/dispatches',
  getParentRoute: () => OfficerRoute,
} as any)
const OfficerIssueRoute = OfficerIssueRouteImport.update({
  id: '/issue',
  path: '/issue',
  getParentRoute: () => OfficerRoute,
} as any)
const OfficerScanRoute = OfficerScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => OfficerRoute,
} as any)
const OfficersIndexRoute = OfficersIndexRouteImport.update({
  id: '/officers/',
  path: '/officers/',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficersBadgeRoute = OfficersBadgeRouteImport.update({
  id: '/officers/$badge',
  path: '/officers/$badge',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficersShiftsRoute = OfficersShiftsRouteImport.update({
  id: '/officers/shifts',
  path: '/officers/shifts',
  getParentRoute: () => rootRouteImport,
} as any)
const VehiclesIndexRoute = VehiclesIndexRouteImport.update({
  id: '/vehicles/',
  path: '/vehicles/',
  getParentRoute: () => rootRouteImport,
} as any)
const VehiclesPlateRoute = VehiclesPlateRouteImport.update({
  id: '/vehicles/$plate',
  path: '/vehicles/$plate',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalPayCitationIdRoute = PortalPayCitationIdRouteImport.update({
  id: '/portal/pay/$citationId',
  path: '/portal/pay/$citationId',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalReceiptCitationIdRoute = PortalReceiptCitationIdRouteImport.update({
  id: '/portal/receipt/$citationId',
  path: '/portal/receipt/$citationId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/advisories': typeof AdvisoriesRoute
  '/ai-training': typeof AiTrainingRoute
  '/analytics': typeof AnalyticsRouteWithChildren
  '/audit-logs': typeof AuditLogsRoute
  '/automation': typeof AutomationRoute
  '/citations': typeof CitationsRoute
  '/citizen': typeof CitizenRoute
  '/communications': typeof CommunicationsRoute
  '/dashboard': typeof DashboardRoute
  '/developer': typeof DeveloperRoute
  '/dispatch': typeof DispatchRoute
  '/dispatch-hotline': typeof DispatchHotlineRoute
  '/disputes': typeof DisputesRoute
  '/finance': typeof FinanceRoute
  '/finance-analytics': typeof FinanceAnalyticsRoute
  '/infrastructure': typeof InfrastructureRoute
  '/iot': typeof IotRoute
  '/lookup': typeof LookupRoute
  '/map': typeof MapRoute
  '/officer': typeof OfficerRouteWithChildren
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/sla-performance': typeof SlaPerformanceRoute
  '/transport': typeof TransportRoute
  '/tv-display': typeof TvDisplayRoute
  '/violations': typeof ViolationsRoute
  '/analytics/heatmaps': typeof AnalyticsHeatmapsRoute
  '/cameras/$code': typeof CamerasCodeRoute
  '/officer/dispatches': typeof OfficerDispatchesRoute
  '/officer/issue': typeof OfficerIssueRoute
  '/officer/scan': typeof OfficerScanRoute
  '/officers/$badge': typeof OfficersBadgeRoute
  '/officers/shifts': typeof OfficersShiftsRoute
  '/vehicles/$plate': typeof VehiclesPlateRoute
  '/cameras/': typeof CamerasIndexRoute
  '/officer/': typeof OfficerIndexRoute
  '/officers/': typeof OfficersIndexRoute
  '/vehicles/': typeof VehiclesIndexRoute
  '/portal/pay/$citationId': typeof PortalPayCitationIdRoute
  '/portal/receipt/$citationId': typeof PortalReceiptCitationIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/advisories': typeof AdvisoriesRoute
  '/ai-training': typeof AiTrainingRoute
  '/analytics': typeof AnalyticsRouteWithChildren
  '/audit-logs': typeof AuditLogsRoute
  '/automation': typeof AutomationRoute
  '/citations': typeof CitationsRoute
  '/citizen': typeof CitizenRoute
  '/communications': typeof CommunicationsRoute
  '/dashboard': typeof DashboardRoute
  '/developer': typeof DeveloperRoute
  '/dispatch': typeof DispatchRoute
  '/dispatch-hotline': typeof DispatchHotlineRoute
  '/disputes': typeof DisputesRoute
  '/finance': typeof FinanceRoute
  '/finance-analytics': typeof FinanceAnalyticsRoute
  '/infrastructure': typeof InfrastructureRoute
  '/iot': typeof IotRoute
  '/lookup': typeof LookupRoute
  '/map': typeof MapRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/sla-performance': typeof SlaPerformanceRoute
  '/transport': typeof TransportRoute
  '/tv-display': typeof TvDisplayRoute
  '/violations': typeof ViolationsRoute
  '/analytics/heatmaps': typeof AnalyticsHeatmapsRoute
  '/cameras/$code': typeof CamerasCodeRoute
  '/officer/dispatches': typeof OfficerDispatchesRoute
  '/officer/issue': typeof OfficerIssueRoute
  '/officer/scan': typeof OfficerScanRoute
  '/officers/$badge': typeof OfficersBadgeRoute
  '/officers/shifts': typeof OfficersShiftsRoute
  '/vehicles/$plate': typeof VehiclesPlateRoute
  '/cameras': typeof CamerasIndexRoute
  '/officer': typeof OfficerIndexRoute
  '/officers': typeof OfficersIndexRoute
  '/vehicles': typeof VehiclesIndexRoute
  '/portal/pay/$citationId': typeof PortalPayCitationIdRoute
  '/portal/receipt/$citationId': typeof PortalReceiptCitationIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/advisories': typeof AdvisoriesRoute
  '/ai-training': typeof AiTrainingRoute
  '/analytics': typeof AnalyticsRouteWithChildren
  '/audit-logs': typeof AuditLogsRoute
  '/automation': typeof AutomationRoute
  '/citations': typeof CitationsRoute
  '/citizen': typeof CitizenRoute
  '/communications': typeof CommunicationsRoute
  '/dashboard': typeof DashboardRoute
  '/developer': typeof DeveloperRoute
  '/dispatch': typeof DispatchRoute
  '/dispatch-hotline': typeof DispatchHotlineRoute
  '/disputes': typeof DisputesRoute
  '/finance': typeof FinanceRoute
  '/finance-analytics': typeof FinanceAnalyticsRoute
  '/infrastructure': typeof InfrastructureRoute
  '/iot': typeof IotRoute
  '/lookup': typeof LookupRoute
  '/map': typeof MapRoute
  '/officer': typeof OfficerRouteWithChildren
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/sla-performance': typeof SlaPerformanceRoute
  '/transport': typeof TransportRoute
  '/tv-display': typeof TvDisplayRoute
  '/violations': typeof ViolationsRoute
  '/analytics/heatmaps': typeof AnalyticsHeatmapsRoute
  '/cameras/$code': typeof CamerasCodeRoute
  '/officer/dispatches': typeof OfficerDispatchesRoute
  '/officer/issue': typeof OfficerIssueRoute
  '/officer/scan': typeof OfficerScanRoute
  '/officers/$badge': typeof OfficersBadgeRoute
  '/officers/shifts': typeof OfficersShiftsRoute
  '/vehicles/$plate': typeof VehiclesPlateRoute
  '/cameras/': typeof CamerasIndexRoute
  '/officer/': typeof OfficerIndexRoute
  '/officers/': typeof OfficersIndexRoute
  '/vehicles/': typeof VehiclesIndexRoute
  '/portal/pay/$citationId': typeof PortalPayCitationIdRoute
  '/portal/receipt/$citationId': typeof PortalReceiptCitationIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/advisories'
    | '/ai-training'
    | '/analytics'
    | '/audit-logs'
    | '/automation'
    | '/citations'
    | '/citizen'
    | '/communications'
    | '/dashboard'
    | '/developer'
    | '/dispatch'
    | '/dispatch-hotline'
    | '/disputes'
    | '/finance'
    | '/finance-analytics'
    | '/infrastructure'
    | '/iot'
    | '/lookup'
    | '/map'
    | '/officer'
    | '/reports'
    | '/settings'
    | '/sla-performance'
    | '/transport'
    | '/tv-display'
    | '/violations'
    | '/analytics/heatmaps'
    | '/cameras/$code'
    | '/officer/dispatches'
    | '/officer/issue'
    | '/officer/scan'
    | '/officers/$badge'
    | '/officers/shifts'
    | '/vehicles/$plate'
    | '/cameras/'
    | '/officer/'
    | '/officers/'
    | '/vehicles/'
    | '/portal/pay/$citationId'
    | '/portal/receipt/$citationId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/advisories'
    | '/ai-training'
    | '/analytics'
    | '/audit-logs'
    | '/automation'
    | '/citations'
    | '/citizen'
    | '/communications'
    | '/dashboard'
    | '/developer'
    | '/dispatch'
    | '/dispatch-hotline'
    | '/disputes'
    | '/finance'
    | '/finance-analytics'
    | '/infrastructure'
    | '/iot'
    | '/lookup'
    | '/map'
    | '/reports'
    | '/settings'
    | '/sla-performance'
    | '/transport'
    | '/tv-display'
    | '/violations'
    | '/analytics/heatmaps'
    | '/cameras/$code'
    | '/officer/dispatches'
    | '/officer/issue'
    | '/officer/scan'
    | '/officers/$badge'
    | '/officers/shifts'
    | '/vehicles/$plate'
    | '/cameras'
    | '/officer'
    | '/officers'
    | '/vehicles'
    | '/portal/pay/$citationId'
    | '/portal/receipt/$citationId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/advisories'
    | '/ai-training'
    | '/analytics'
    | '/audit-logs'
    | '/automation'
    | '/citations'
    | '/citizen'
    | '/communications'
    | '/dashboard'
    | '/developer'
    | '/dispatch'
    | '/dispatch-hotline'
    | '/disputes'
    | '/finance'
    | '/finance-analytics'
    | '/infrastructure'
    | '/iot'
    | '/lookup'
    | '/map'
    | '/officer'
    | '/reports'
    | '/settings'
    | '/sla-performance'
    | '/transport'
    | '/tv-display'
    | '/violations'
    | '/analytics/heatmaps'
    | '/cameras/$code'
    | '/officer/dispatches'
    | '/officer/issue'
    | '/officer/scan'
    | '/officers/$badge'
    | '/officers/shifts'
    | '/vehicles/$plate'
    | '/cameras/'
    | '/officer/'
    | '/officers/'
    | '/vehicles/'
    | '/portal/pay/$citationId'
    | '/portal/receipt/$citationId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AdvisoriesRoute: typeof AdvisoriesRoute
  AiTrainingRoute: typeof AiTrainingRoute
  AnalyticsRoute: typeof AnalyticsRouteWithChildren
  AuditLogsRoute: typeof AuditLogsRoute
  AutomationRoute: typeof AutomationRoute
  CitationsRoute: typeof CitationsRoute
  CitizenRoute: typeof CitizenRoute
  CommunicationsRoute: typeof CommunicationsRoute
  DashboardRoute: typeof DashboardRoute
  DeveloperRoute: typeof DeveloperRoute
  DispatchRoute: typeof DispatchRoute
  DispatchHotlineRoute: typeof DispatchHotlineRoute
  DisputesRoute: typeof DisputesRoute
  FinanceRoute: typeof FinanceRoute
  FinanceAnalyticsRoute: typeof FinanceAnalyticsRoute
  InfrastructureRoute: typeof InfrastructureRoute
  IotRoute: typeof IotRoute
  LookupRoute: typeof LookupRoute
  MapRoute: typeof MapRoute
  OfficerRoute: typeof OfficerRouteWithChildren
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  SlaPerformanceRoute: typeof SlaPerformanceRoute
  TransportRoute: typeof TransportRoute
  TvDisplayRoute: typeof TvDisplayRoute
  ViolationsRoute: typeof ViolationsRoute
  CamerasCodeRoute: typeof CamerasCodeRoute
  OfficersBadgeRoute: typeof OfficersBadgeRoute
  OfficersShiftsRoute: typeof OfficersShiftsRoute
  VehiclesPlateRoute: typeof VehiclesPlateRoute
  CamerasIndexRoute: typeof CamerasIndexRoute
  OfficersIndexRoute: typeof OfficersIndexRoute
  VehiclesIndexRoute: typeof VehiclesIndexRoute
  PortalPayCitationIdRoute: typeof PortalPayCitationIdRoute
  PortalReceiptCitationIdRoute: typeof PortalReceiptCitationIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advisories': {
      id: '/advisories'
      path: '/advisories'
      fullPath: '/advisories'
      preLoaderRoute: typeof AdvisoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-training': {
      id: '/ai-training'
      path: '/ai-training'
      fullPath: '/ai-training'
      preLoaderRoute: typeof AiTrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit-logs': {
      id: '/audit-logs'
      path: '/audit-logs'
      fullPath: '/audit-logs'
      preLoaderRoute: typeof AuditLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automation': {
      id: '/automation'
      path: '/automation'
      fullPath: '/automation'
      preLoaderRoute: typeof AutomationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/citations': {
      id: '/citations'
      path: '/citations'
      fullPath: '/citations'
      preLoaderRoute: typeof CitationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/citizen': {
      id: '/citizen'
      path: '/citizen'
      fullPath: '/citizen'
      preLoaderRoute: typeof CitizenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/communications': {
      id: '/communications'
      path: '/communications'
      fullPath: '/communications'
      preLoaderRoute: typeof CommunicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developer': {
      id: '/developer'
      path: '/developer'
      fullPath: '/developer'
      preLoaderRoute: typeof DeveloperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dispatch': {
      id: '/dispatch'
      path: '/dispatch'
      fullPath: '/dispatch'
      preLoaderRoute: typeof DispatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dispatch-hotline': {
      id: '/dispatch-hotline'
      path: '/dispatch-hotline'
      fullPath: '/dispatch-hotline'
      preLoaderRoute: typeof DispatchHotlineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disputes': {
      id: '/disputes'
      path: '/disputes'
      fullPath: '/disputes'
      preLoaderRoute: typeof DisputesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance': {
      id: '/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof FinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance-analytics': {
      id: '/finance-analytics'
      path: '/finance-analytics'
      fullPath: '/finance-analytics'
      preLoaderRoute: typeof FinanceAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/infrastructure': {
      id: '/infrastructure'
      path: '/infrastructure'
      fullPath: '/infrastructure'
      preLoaderRoute: typeof InfrastructureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iot': {
      id: '/iot'
      path: '/iot'
      fullPath: '/iot'
      preLoaderRoute: typeof IotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lookup': {
      id: '/lookup'
      path: '/lookup'
      fullPath: '/lookup'
      preLoaderRoute: typeof LookupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/officer': {
      id: '/officer'
      path: '/officer'
      fullPath: '/officer'
      preLoaderRoute: typeof OfficerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sla-performance': {
      id: '/sla-performance'
      path: '/sla-performance'
      fullPath: '/sla-performance'
      preLoaderRoute: typeof SlaPerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transport': {
      id: '/transport'
      path: '/transport'
      fullPath: '/transport'
      preLoaderRoute: typeof TransportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tv-display': {
      id: '/tv-display'
      path: '/tv-display'
      fullPath: '/tv-display'
      preLoaderRoute: typeof TvDisplayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/violations': {
      id: '/violations'
      path: '/violations'
      fullPath: '/violations'
      preLoaderRoute: typeof ViolationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics/heatmaps': {
      id: '/analytics/heatmaps'
      path: '/heatmaps'
      fullPath: '/analytics/heatmaps'
      preLoaderRoute: typeof AnalyticsHeatmapsRouteImport
      parentRoute: typeof AnalyticsRoute
    }
    '/cameras/': {
      id: '/cameras/'
      path: '/cameras'
      fullPath: '/cameras/'
      preLoaderRoute: typeof CamerasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cameras/$code': {
      id: '/cameras/$code'
      path: '/cameras/$code'
      fullPath: '/cameras/$code'
      preLoaderRoute: typeof CamerasCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/officer/': {
      id: '/officer/'
      path: '/'
      fullPath: '/officer/'
      preLoaderRoute: typeof OfficerIndexRouteImport
      parentRoute: typeof OfficerRoute
    }
    '/officer/dispatches': {
      id: '/officer/dispatches'
      path: '/dispatches'
      fullPath: '/officer/dispatches'
      preLoaderRoute: typeof OfficerDispatchesRouteImport
      parentRoute: typeof OfficerRoute
    }
    '/officer/issue': {
      id: '/officer/issue'
      path: '/issue'
      fullPath: '/officer/issue'
      preLoaderRoute: typeof OfficerIssueRouteImport
      parentRoute: typeof OfficerRoute
    }
    '/officer/scan': {
      id: '/officer/scan'
      path: '/scan'
      fullPath: '/officer/scan'
      preLoaderRoute: typeof OfficerScanRouteImport
      parentRoute: typeof OfficerRoute
    }
    '/officers/': {
      id: '/officers/'
      path: '/officers'
      fullPath: '/officers/'
      preLoaderRoute: typeof OfficersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/officers/$badge': {
      id: '/officers/$badge'
      path: '/officers/$badge'
      fullPath: '/officers/$badge'
      preLoaderRoute: typeof OfficersBadgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/officers/shifts': {
      id: '/officers/shifts'
      path: '/officers/shifts'
      fullPath: '/officers/shifts'
      preLoaderRoute: typeof OfficersShiftsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vehicles/': {
      id: '/vehicles/'
      path: '/vehicles'
      fullPath: '/vehicles/'
      preLoaderRoute: typeof VehiclesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vehicles/$plate': {
      id: '/vehicles/$plate'
      path: '/vehicles/$plate'
      fullPath: '/vehicles/$plate'
      preLoaderRoute: typeof VehiclesPlateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/pay/$citationId': {
      id: '/portal/pay/$citationId'
      path: '/portal/pay/$citationId'
      fullPath: '/portal/pay/$citationId'
      preLoaderRoute: typeof PortalPayCitationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/receipt/$citationId': {
      id: '/portal/receipt/$citationId'
      path: '/portal/receipt/$citationId'
      fullPath: '/portal/receipt/$citationId'
      preLoaderRoute: typeof PortalReceiptCitationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AnalyticsRouteChildren {
  AnalyticsHeatmapsRoute: typeof AnalyticsHeatmapsRoute
}

const AnalyticsRouteChildren: AnalyticsRouteChildren = {
  AnalyticsHeatmapsRoute: AnalyticsHeatmapsRoute,
}

const AnalyticsRouteWithChildren = AnalyticsRoute._addFileChildren(
  AnalyticsRouteChildren,
)

interface OfficerRouteChildren {
  OfficerDispatchesRoute: typeof OfficerDispatchesRoute
  OfficerIssueRoute: typeof OfficerIssueRoute
  OfficerScanRoute: typeof OfficerScanRoute
  OfficerIndexRoute: typeof OfficerIndexRoute
}

const OfficerRouteChildren: OfficerRouteChildren = {
  OfficerDispatchesRoute: OfficerDispatchesRoute,
  OfficerIssueRoute: OfficerIssueRoute,
  OfficerScanRoute: OfficerScanRoute,
  OfficerIndexRoute: OfficerIndexRoute,
}

const OfficerRouteWithChildren =
  OfficerRoute._addFileChildren(OfficerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AdvisoriesRoute: AdvisoriesRoute,
  AiTrainingRoute: AiTrainingRoute,
  AnalyticsRoute: AnalyticsRouteWithChildren,
  AuditLogsRoute: AuditLogsRoute,
  AutomationRoute: AutomationRoute,
  CitationsRoute: CitationsRoute,
  CitizenRoute: CitizenRoute,
  CommunicationsRoute: CommunicationsRoute,
  DashboardRoute: DashboardRoute,
  DeveloperRoute: DeveloperRoute,
  DispatchRoute: DispatchRoute,
  DispatchHotlineRoute: DispatchHotlineRoute,
  DisputesRoute: DisputesRoute,
  FinanceRoute: FinanceRoute,
  FinanceAnalyticsRoute: FinanceAnalyticsRoute,
  InfrastructureRoute: InfrastructureRoute,
  IotRoute: IotRoute,
  LookupRoute: LookupRoute,
  MapRoute: MapRoute,
  OfficerRoute: OfficerRouteWithChildren,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  SlaPerformanceRoute: SlaPerformanceRoute,
  TransportRoute: TransportRoute,
  TvDisplayRoute: TvDisplayRoute,
  ViolationsRoute: ViolationsRoute,
  CamerasCodeRoute: CamerasCodeRoute,
  OfficersBadgeRoute: OfficersBadgeRoute,
  OfficersShiftsRoute: OfficersShiftsRoute,
  VehiclesPlateRoute: VehiclesPlateRoute,
  CamerasIndexRoute: CamerasIndexRoute,
  OfficersIndexRoute: OfficersIndexRoute,
  VehiclesIndexRoute: VehiclesIndexRoute,
  PortalPayCitationIdRoute: PortalPayCitationIdRoute,
  PortalReceiptCitationIdRoute: PortalReceiptCitationIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
