/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as CitationsRouteImport } from './routes/citations'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DispatchRouteImport } from './routes/dispatch'
import { Route as LookupRouteImport } from './routes/lookup'
import { Route as MapRouteImport } from './routes/map'
import { Route as ViolationsRouteImport } from './routes/violations'
import { Route as CamerasIndexRouteImport } from './routes/cameras.index'
import { Route as CamerasCodeRouteImport } from './routes/cameras.$code'
import { Route as OfficersIndexRouteImport } from './routes/officers.index'
import { Route as OfficersBadgeRouteImport } from './routes/officers.$badge'
import { Route as VehiclesIndexRouteImport } from './routes/vehicles.index'
import { Route as VehiclesPlateRouteImport } from './routes/vehicles.$plate'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const CitationsRoute = CitationsRouteImport.update({
  id: '/citations',
  path: '/citations',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DispatchRoute = DispatchRouteImport.update({
  id: '/dispatch',
  path: '/dispatch',
  getParentRoute: () => rootRouteImport,
} as any)
const LookupRoute = LookupRouteImport.update({
  id: '/lookup',
  path: '/lookup',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const ViolationsRoute = ViolationsRouteImport.update({
  id: '/violations',
  path: '/violations',
  getParentRoute: () => rootRouteImport,
} as any)
const CamerasIndexRoute = CamerasIndexRouteImport.update({
  id: '/cameras/',
  path: '/cameras/',
  getParentRoute: () => rootRouteImport,
} as any)
const CamerasCodeRoute = CamerasCodeRouteImport.update({
  id: '/cameras/$code',
  path: '/cameras/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficersIndexRoute = OfficersIndexRouteImport.update({
  id: '/officers/',
  path: '/officers/',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficersBadgeRoute = OfficersBadgeRouteImport.update({
  id: '/officers/$badge',
  path: '/officers/$badge',
  getParentRoute: () => rootRouteImport,
} as any)
const VehiclesIndexRoute = VehiclesIndexRouteImport.update({
  id: '/vehicles/',
  path: '/vehicles/',
  getParentRoute: () => rootRouteImport,
} as any)
const VehiclesPlateRoute = VehiclesPlateRouteImport.update({
  id: '/vehicles/$plate',
  path: '/vehicles/$plate',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/citations': typeof CitationsRoute
  '/dashboard': typeof DashboardRoute
  '/dispatch': typeof DispatchRoute
  '/lookup': typeof LookupRoute
  '/map': typeof MapRoute
  '/violations': typeof ViolationsRoute
  '/cameras/$code': typeof CamerasCodeRoute
  '/officers/$badge': typeof OfficersBadgeRoute
  '/vehicles/$plate': typeof VehiclesPlateRoute
  '/cameras/': typeof CamerasIndexRoute
  '/officers/': typeof OfficersIndexRoute
  '/vehicles/': typeof VehiclesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/citations': typeof CitationsRoute
  '/dashboard': typeof DashboardRoute
  '/dispatch': typeof DispatchRoute
  '/lookup': typeof LookupRoute
  '/map': typeof MapRoute
  '/violations': typeof ViolationsRoute
  '/cameras/$code': typeof CamerasCodeRoute
  '/officers/$badge': typeof OfficersBadgeRoute
  '/vehicles/$plate': typeof VehiclesPlateRoute
  '/cameras': typeof CamerasIndexRoute
  '/officers': typeof OfficersIndexRoute
  '/vehicles': typeof VehiclesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/citations': typeof CitationsRoute
  '/dashboard': typeof DashboardRoute
  '/dispatch': typeof DispatchRoute
  '/lookup': typeof LookupRoute
  '/map': typeof MapRoute
  '/violations': typeof ViolationsRoute
  '/cameras/$code': typeof CamerasCodeRoute
  '/officers/$badge': typeof OfficersBadgeRoute
  '/vehicles/$plate': typeof VehiclesPlateRoute
  '/cameras/': typeof CamerasIndexRoute
  '/officers/': typeof OfficersIndexRoute
  '/vehicles/': typeof VehiclesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/citations'
    | '/dashboard'
    | '/dispatch'
    | '/lookup'
    | '/map'
    | '/violations'
    | '/cameras/$code'
    | '/officers/$badge'
    | '/vehicles/$plate'
    | '/cameras/'
    | '/officers/'
    | '/vehicles/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/citations'
    | '/dashboard'
    | '/dispatch'
    | '/lookup'
    | '/map'
    | '/violations'
    | '/cameras/$code'
    | '/officers/$badge'
    | '/vehicles/$plate'
    | '/cameras'
    | '/officers'
    | '/vehicles'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/citations'
    | '/dashboard'
    | '/dispatch'
    | '/lookup'
    | '/map'
    | '/violations'
    | '/cameras/$code'
    | '/officers/$badge'
    | '/vehicles/$plate'
    | '/cameras/'
    | '/officers/'
    | '/vehicles/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  CitationsRoute: typeof CitationsRoute
  DashboardRoute: typeof DashboardRoute
  DispatchRoute: typeof DispatchRoute
  LookupRoute: typeof LookupRoute
  MapRoute: typeof MapRoute
  ViolationsRoute: typeof ViolationsRoute
  CamerasCodeRoute: typeof CamerasCodeRoute
  OfficersBadgeRoute: typeof OfficersBadgeRoute
  VehiclesPlateRoute: typeof VehiclesPlateRoute
  CamerasIndexRoute: typeof CamerasIndexRoute
  OfficersIndexRoute: typeof OfficersIndexRoute
  VehiclesIndexRoute: typeof VehiclesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/citations': {
      id: '/citations'
      path: '/citations'
      fullPath: '/citations'
      preLoaderRoute: typeof CitationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dispatch': {
      id: '/dispatch'
      path: '/dispatch'
      fullPath: '/dispatch'
      preLoaderRoute: typeof DispatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lookup': {
      id: '/lookup'
      path: '/lookup'
      fullPath: '/lookup'
      preLoaderRoute: typeof LookupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/violations': {
      id: '/violations'
      path: '/violations'
      fullPath: '/violations'
      preLoaderRoute: typeof ViolationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cameras/': {
      id: '/cameras/'
      path: '/cameras'
      fullPath: '/cameras/'
      preLoaderRoute: typeof CamerasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cameras/$code': {
      id: '/cameras/$code'
      path: '/cameras/$code'
      fullPath: '/cameras/$code'
      preLoaderRoute: typeof CamerasCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/officers/': {
      id: '/officers/'
      path: '/officers'
      fullPath: '/officers/'
      preLoaderRoute: typeof OfficersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/officers/$badge': {
      id: '/officers/$badge'
      path: '/officers/$badge'
      fullPath: '/officers/$badge'
      preLoaderRoute: typeof OfficersBadgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vehicles/': {
      id: '/vehicles/'
      path: '/vehicles'
      fullPath: '/vehicles/'
      preLoaderRoute: typeof VehiclesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vehicles/$plate': {
      id: '/vehicles/$plate'
      path: '/vehicles/$plate'
      fullPath: '/vehicles/$plate'
      preLoaderRoute: typeof VehiclesPlateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  CitationsRoute: CitationsRoute,
  DashboardRoute: DashboardRoute,
  DispatchRoute: DispatchRoute,
  LookupRoute: LookupRoute,
  MapRoute: MapRoute,
  ViolationsRoute: ViolationsRoute,
  CamerasCodeRoute: CamerasCodeRoute,
  OfficersBadgeRoute: OfficersBadgeRoute,
  VehiclesPlateRoute: VehiclesPlateRoute,
  CamerasIndexRoute: CamerasIndexRoute,
  OfficersIndexRoute: OfficersIndexRoute,
  VehiclesIndexRoute: VehiclesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
